from .home import Homepage
from .signin import Signin
from .signup import Signup
from .home import Home
from .cart import Cart
from .signin import logout, sellerlogout
from .seller_home import SellerHome
from .addcatalog import AddCatalog
from .editcatalog import EditCatalog
from .sellercatalogs import SellerCatalogs, deleteCatalog
from .checkout import Checkout
from .order import OrderView
from .editprofile import EditProfile
from .sellereditprofile import SellerEditProfile
from .orderstatuschange import OrderStatusChange
from .rating import Ratings
from .sellerpendingorders import SellerPendingOrders
from .sellercompleteorders import SellerCompleteOrders
from .buyerpendingorders import BuyerPendingOrders
from .buyercompleteorders import BuyerCompleteOrders
from .adminpanel import AdminPanel
from .editprofile_admin import EditProfileAdmin
from .conflictonorder import ConflictOnOrder
from .postconflict import PostConflict
from .conflictstatuschange import ConflictStatusChange
from .adminbcompletec import AdminbCompleteConflicts
from .adminbpendingc import AdminbPendingConflicts
from .payment import PaymentPageView
from .charge import Charge