# Generated by Django 4.0 on 2022-01-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_users_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contact',
            field=models.CharField(max_length=11),
        ),
    ]
