# Generated by Django 4.0 on 2022-01-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_users_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='StoreUsers',
        ),
        migrations.AlterModelTable(
            name='storeusers',
            table='storeusers',
        ),
    ]
