# Generated by Django 4.0 on 2022-01-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_users_storeusers_alter_storeusers_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreUsers',
            new_name='StoreUser',
        ),
        migrations.AlterModelTable(
            name='storeuser',
            table='storeuser',
        ),
    ]
