# Generated by Django 4.0 on 2022-01-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_storeusers_storeuser_alter_storeuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='storeuser',
            table='storeUser',
        ),
    ]
