# Generated by Django 4.0 on 2022-01-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_storeuser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogid', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('seller', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('ears', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'catalog',
            },
        ),
    ]
