# Generated by Django 4.0 on 2022-01-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='contact',
            field=models.IntegerField(max_length=11),
        ),
    ]
