# Generated by Django 4.0 on 2022-01-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_storeuser_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='contact',
            field=models.CharField(max_length=11),
        ),
    ]
