# Generated by Django 4.0 on 2022-01-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_storeuser_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='ears',
            field=models.IntegerField(max_length=20),
        ),
    ]
