# Generated by Django 4.0 on 2022-01-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_catalog_ears'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='ears',
            field=models.CharField(max_length=20),
        ),
    ]
