# Generated by Django 4.0 on 2022-01-03 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_filter_alter_catalog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='breed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.filter'),
        ),
    ]
