# Generated by Django 4.0 on 2022-01-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(default='', max_length=30),
        ),
    ]
