# Generated by Django 4.0 on 2022-01-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='catalogid',
        ),
    ]
