# Generated by Django 4.0 on 2022-01-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_catalog_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
