# Generated by Django 4.0 on 2022-01-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='ratings',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='catalog',
            name='star1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catalog',
            name='star2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catalog',
            name='star3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catalog',
            name='star4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catalog',
            name='star5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catalog',
            name='totalratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='feedback',
            field=models.BooleanField(default=False),
        ),
    ]
