# Generated by Django 4.0 on 2022-04-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_catalog_ratings_catalog_star1_catalog_star2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='address',
            field=models.CharField(default='temporary address', max_length=100),
            preserve_default=False,
        ),
    ]
