# Generated by Django 4.0 on 2022-06-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_storeuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
