# Generated by Django 4.0 on 2022-06-23 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_storeuser_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raisedby_name', models.CharField(default='', max_length=50)),
                ('raisedagainst_name', models.CharField(default='', max_length=50)),
                ('raisedby_email', models.CharField(default='', max_length=50)),
                ('raisedagainst_email', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('conflict_subject', models.CharField(default='', max_length=40)),
                ('conflict_description', models.CharField(default='', max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'conflict',
            },
        ),
    ]
