# Generated by Django 4.0 on 2022-06-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_conflict'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflict',
            name='raisedagainst_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='conflict',
            name='raisedby_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
